/* ===========
   AZ2NEXTHOOPS scouting data (SOURCE OF TRUTH for the public site)
   Generated by Publish on 2026-10-06T02:28:46.373Z
   Replace js/data.js on your host with this file. See README.md.
=========== */
window.SEED_DATA = {
  "dataVersion": 2,
  "brand": "AZ2NEXTHOOPS",
  "tagline": "Scouting Reports & Ranked Boards",
  "levels": [
    "NBA",
    "College",
    "G-League",
    "International"
  ],
  "positions": [
    "PG",
    "SG",
    "SF",
    "PF",
    "C"
  ],
  "boardCategories": [
    {
      "id": "overall",
      "label": "Overall Board",
      "byPosition": false
    },
    {
      "id": "shooters",
      "label": "Best Shooters",
      "byPosition": false
    },
    {
      "id": "defenders",
      "label": "Best Defenders",
      "byPosition": false
    },
    {
      "id": "guards",
      "label": "Best Guards",
      "byPosition": true
    },
    {
      "id": "wings",
      "label": "Best Wings",
      "byPosition": true
    },
    {
      "id": "bigs",
      "label": "Best Bigs",
      "byPosition": true
    },
    {
      "id": "twoway",
      "label": "Best 2-Way Candidates",
      "byPosition": false
    }
  ],
  "players": [
    {
      "id": "p_sample_carter",
      "name": "[SAMPLE] DeShawn Carter",
      "level": "College",
      "position": "PG",
      "team": "Lakeside State (sample)",
      "vitals": {
        "height": "6'2\"",
        "weight": "185",
        "age": "20",
        "classYear": "Sophomore",
        "handedness": "Right"
      },
      "objective": "Efficient, low-maintenance lead guard who projects as a reliable backup floor general. Buy-in role player whose value comes from decision-making and catch-and-shoot reliability rather than self-creation volume.",
      "role": "Backup PG/second-unit lead guard; developmental 3-and-D point if the frame fills out.",
      "strengths": [
        "Repeatable catch-and-shoot mechanics that hold up from NBA three-point range.",
        "Quickly reads ball-screen coverages and makes the simple, correct pass.",
        "Low turnover profile within structured half-court offense."
      ],
      "questions": [
        "Can he stay in front of bigger, longer NBA point guards?",
        "Does his handle survive extended pressure and blitzes?",
        "Is there enough burst to turn the corner against elite closeouts?"
      ],
      "analysis": {
        "shooting": {
          "mechanics": "Clean, repeatable set point; elbows aligned; consistent one-motion release. Holds form under fatigue in the sample reviewed.",
          "rangeVolume": "38% from three on ~4 attempts/game-volume is in the flow of the offense, not forced. Range translates to the NBA line on open looks.",
          "shotSelection": "Understands spacing and role; rarely forces. Downhill + catch-and-shoot diet is clean almost no hero-ball possessions.",
          "offMovement": "Coming off flares and DHOs the footwork is a repeatable 1-2. Reliable relocation when the primary action breaks."
        },
        "creation": {
          "changeOfPace": "",
          "separation": "",
          "finishing": "",
          "selfVsScheme": ""
        },
        "passing": {
          "liveVision": "Sees the second side off live dribble and delivers ahead of the rotation.",
          "processing": "Anticipates tag rotations; rarely late on the read.",
          "decisions": "",
          "feel": ""
        },
        "defense": {
          "onBall": "",
          "offBall": "",
          "versatility": "",
          "effort": ""
        },
        "athletic": {
          "sizeLength": "",
          "speed": "Average burst; plays at a controlled pace rather than exploding by defenders.",
          "vertical": "",
          "strength": ""
        },
        "rebounding": {
          "boxOut": "",
          "timing": ""
        },
        "screening": "",
        "physicality": "",
        "offball": {
          "cutting": "",
          "spacing": "",
          "relocation": "",
          "navigation": ""
        },
        "makeup": {
          "motor": "",
          "coachability": "",
          "adversity": "",
          "leadership": ""
        }
      },
      "context": {
        "age": "2
